# QUITA version (obsoleto)
services:
  agrosync-api:
    build: .
    ports:
      - "8282:8282"
    volumes:
      - ./app:/app/app
      - ./creds:/app/app/creds:ro  # Monta carpeta creds como solo lectura
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
